In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df["Pclass"].unique()

array([3, 1, 2])

In [5]:
df["Survived"].unique()

array([0, 1])

In [6]:
dff=df[["Survived","Pclass"]].dropna()

In [7]:
dff

     Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

In [17]:
survived=[
    len(dff[(dff["Survived"]==0) & (dff["Pclass"]==1)]),
    len(dff[(dff["Survived"]==0) & (dff["Pclass"]==2)]),
    len(dff[(dff["Survived"]==0) & (dff["Pclass"]==3)])
]

In [18]:
survived

[80, 97, 372]

In [19]:
unsurvived=[
    len(dff[(dff["Survived"]==1) & (dff["Pclass"]==1)]),
    len(dff[(dff["Survived"]==1) & (dff["Pclass"]==2)]),
    len(dff[(dff["Survived"]==1) & (dff["Pclass"]==3)])
]

In [20]:
unsurvived

[136, 87, 119]

In [21]:
observed=np.array([survived,unsurvived])

In [22]:
observed

array([[ 80,  97, 372],
       [136,  87, 119]])

In [23]:
row_sum=np.sum(observed,axis=1)

In [24]:
row_sum

array([549, 342])

In [25]:
col_sum=np.sum(observed,axis=0)

In [26]:
col_sum

array([216, 184, 491])

In [29]:
total_sum=np.sum(observed)

In [30]:
total_sum

np.int64(891)

In [27]:
expected=np.zeros(observed.shape)

In [28]:
expected

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
for i in range(observed.shape[0]):
    for j in range(observed.shape[1]):
        expected[i,j]=(row_sum[i]*col_sum[j])/total_sum

In [33]:
expected

array([[133.09090909, 113.37373737, 302.53535354],
       [ 82.90909091,  70.62626263, 188.46464646]])

In [34]:
chi2_value=np.sum(((observed-expected)**2)/expected)

In [35]:
chi2_value

np.float64(102.88898875696056)

In [36]:
dof=2

In [37]:
critical_value=5.991

In [38]:
from scipy.stats import chi2_contingency

In [42]:
chi,p_value,dof,expected=chi2_contingency(observed)

In [43]:
chi

np.float64(102.88898875696056)

In [44]:
p_value

np.float64(4.549251711298793e-23)