In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("diet_recommendation_dataset_1000.csv")

In [3]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic
999,37,1,175,55,18.0,1,168,161,1,Diabetic

In [4]:
X=df.drop(columns=["Diet"])

In [5]:
Y=df["Diet"]

In [6]:
from sklearn.neighbors import LocalOutlierFactor

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
ss=StandardScaler()

In [9]:
X_scaled=ss.fit_transform(X)

In [10]:
X_scaled

array([[ 1.04842048, -0.9530986 , -1.68541151, ...,  0.16460264,
        -1.0232246 ,  1.26976006],
       [ 0.32161252,  1.04920939, -0.0867105 , ..., -0.24391862,
         1.04987878,  1.26976006],
       [-0.69591862, -0.9530986 ,  0.21780398, ..., -1.50090712,
         1.12391819,  1.26976006],
       ...,
       [-1.49540738, -0.9530986 , -0.61961084, ...,  0.00747908,
        -0.82578618, -1.21752703],
       [-0.40519544,  1.04920939,  0.2939326 , ...,  0.73024747,
         0.95115957, -1.21752703],
       [-0.33251464,  1.04920939,  0.59844708, ...,  1.327317  ,
        -1.22066301,  0.02611651]])

In [11]:
lof=LocalOutlierFactor(n_neighbors=20,contamination=0.05)

In [12]:
lof_labels=lof.fit_predict(X_scaled)

In [13]:
lof_labels

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1])

In [14]:
df["LOF"]=lof_labels

In [15]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet,LOF
0,56,0,145,118,56.1,0,131,169,2,Low Carb,-1
1,46,1,166,62,22.5,0,118,253,2,Diabetic,1
2,32,0,170,83,28.7,1,78,256,2,Diabetic,1
3,60,1,162,116,44.2,2,161,199,0,Diabetic,1
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy,1
...,...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic,1
996,43,1,165,52,19.1,2,175,156,2,Diabetic,1
997,21,0,159,70,27.7,1,126,177,0,Low Carb,1
998,36,1,171,41,14.0,2,149,249,0,Diabetic,1
999,37,1,175,55,18.0,1,168,161,1,Diabetic,1

In [16]:
df["LOF"].value_counts()

LOF
 1    950
-1     50
Name: count, dtype: int64

In [17]:
df.columns

Index(['Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI', 'Activity_Level',
       'Sugar_Level', 'Cholesterol', 'Goal', 'Diet', 'LOF'],
      dtype='object')

In [19]:
def LOF_outlier_imputation(df,cols,low=0.05,high=0.95):
    inliner=df[df["LOF"]==1]
    outliers=df[df["LOF"]==-1]
    for col in cols:
        LL=inliner[col].quantile(low)
        UL=inliner[col].quantile(high)
        outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
    new_data=pd.concat([inliner,outliers])
    return new_data

In [20]:
cols=["Age","Height_cm","Weight_kg","BMI","Sugar_Level","Cholesterol"]
new_data=LOF_outlier_imputation(df,cols)

C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2517470649.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers[col]=outliers[col].apply(lambda x:LL if x<=LL else (UL if UL>x else x))

In [21]:
new_data

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet,LOF
1,46.0,1,166.0,62.00,22.500,0,118.0,253.0,2,Diabetic,1
2,32.0,0,170.0,83.00,28.700,1,78.0,256.0,2,Diabetic,1
3,60.0,1,162.0,116.00,44.200,2,161.0,199.0,0,Diabetic,1
4,25.0,0,158.0,61.00,24.400,1,100.0,237.0,1,Heart Healthy,1
5,38.0,0,173.0,82.00,27.400,1,167.0,265.0,2,Diabetic,1
...,...,...,...,...,...,...,...,...,...,...,...
882,64.0,1,148.0,115.00,44.655,2,77.0,271.0,2,Balanced,-1
921,63.0,0,188.0,44.45,15.245,0,77.0,149.0,0,High Protein,-1
954,63.0,1,188.0,115.00,44.655,0,176.0,271.0,2,Diabetic,-1
982,63.0,1,188.0,115.00,44.655,0,77.0,271.0,1,Diabetic,-1
994,63.0,0,148.0,115.00,51.600,2,177.0,271.0,1,Diabetic,-1

In [22]:
check_quantile_df=df.select_dtypes(include="number")
quantile=check_quantile_df.quantile([0.05,0.95])

In [23]:
quantile

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,LOF
0.05,20.0,0.0,147.0,43.95,15.100,0.0,76.00,148.00,0.0,0.9
0.95,63.0,1.0,188.0,115.00,45.415,2.0,175.05,271.05,2.0,1.0

In [24]:
check_quantile_new=new_data.select_dtypes(include="number")
quantile1=check_quantile_new.quantile([0.05,0.95])

In [25]:
quantile1

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,LOF
0.05,20.0,0.0,148.0,44.45,15.245,0.0,77.00,149.00,0.0,0.9
0.95,63.0,1.0,188.0,115.00,45.415,2.0,175.05,271.05,2.0,1.0